# 
num_beams_per_particle: 100

# A reasonable number to start with
num_particles: 200

scan_distance_to_base_link: 0.275 # meters

# rear axle of the racecar
wheelbase: 0.325 # meters

# Limits on the speed and steering angle
max_speed: 4. # meters/second
max_steering_angle: 0.34 # radians

# The rate at which the pose and the lidar publish
update_pose_rate: 0.02

# Lidar simulation parameters
scan_beams: 100
scan_field_of_view: 4.71 # radians

# The distance from the center of the
# rear axis (base_link) to the lidar

# The names of topics to listen and publish to
map_topic: "/map"
scan_topic: "/scan"
odom_topic: "/odom"
