# A reasonable number to start with
num_particles: 200

# The number of lidar beams emitted from
# each particle. This doesn't need to be
# equal to the actual number (>1000)
# so long as you downsample properly
num_beams_per_particle: 100

# The field of view centered around theta=0
scan_field_of_view: 4.71 # radians

# The names of topics to listen and publish to
map_topic: "/map"
scan_topic: "/scan"
odom_topic: "/odom"
